// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBneHugzoBujBfhxFENf1ugkpavrVg0fgk',
    appId: '1:640605406316:web:5c52ed246dc56b72248449',
    messagingSenderId: '640605406316',
    projectId: 'glamour-galleria-app',
    authDomain: 'glamour-galleria-app.firebaseapp.com',
    storageBucket: 'glamour-galleria-app.appspot.com',
    measurementId: 'G-LC2ER2GHTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2YrbfuOgPxFshpCrhw9otDU999tW9bIs',
    appId: '1:640605406316:android:9f12e99e9e943fbf248449',
    messagingSenderId: '640605406316',
    projectId: 'glamour-galleria-app',
    storageBucket: 'glamour-galleria-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyfr7iEJqWz1CyR1g9w895Atxm1sPyeic',
    appId: '1:640605406316:ios:09b7eb42f19f4285248449',
    messagingSenderId: '640605406316',
    projectId: 'glamour-galleria-app',
    storageBucket: 'glamour-galleria-app.appspot.com',
    iosBundleId: 'com.example.onlineShopApp',
  );
}
